geo $http_x_forwarded_for $block {
    205.210.31.0/24          1;
    20.242.69.0/24           1;
    198.235.24.0/24          1;
    194.126.177.82           1;
    172.98.32.34             1;
    51.141.66.107            1;
    40.122.238.0/24          1;
    210.241.233.154          1;
    20.213.22.70             1;
    2001:1640:5::3:d6        1;
    51.107.217.200           1;
    51.11.179.215            1;
    20.28.193.110            1;
    20.216.129.92            1;
    51.120.14.80             1;
    20.121.56.39             1;
    20.0.222.149             1;
    20.163.141.249           1;
    85.31.46.0/24            1;
}

server {
    listen   80; ## listen for ipv4; this line is default and implied
    listen   [::]:80 default ipv6only=on; ## listen for ipv6

    root /var/www/public;
    index index.php;

    # Make site accessible from http://localhost/
    server_name _;

    # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
    sendfile off;

    # Security - Hide nginx version number in error pages and Server header
    server_tokens off;

    client_max_body_size        120M;
    proxy_connect_timeout       605;
    proxy_send_timeout          605;
    proxy_read_timeout          605;
    send_timeout                605;
    keepalive_timeout           605;
    
    set_real_ip_from  172.26.0.0/16;
    real_ip_header    X-Forwarded-For;

    # Add stdout logging
    error_log /dev/stdout info;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    # reduce the data that needs to be sent over network
    gzip on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml application/json text/javascript application/x-javascript application/xml;
    gzip_disable "MSIE [1-6]\.";

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
    
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
        access_log off;
    }

    location /health-check-elb-status {
        access_log off;
        return 200 'ok';
        # because default content-type is application/octet-stream,
        # browser will offer to "save the file"...
        # the next line allows you to see it in the browser so you can test 
        add_header Content-Type text/plain;
    }

    location / {
        if ($block) { 
            return 403; 
        }
        
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # pass the PHP scripts to FastCGI server listening on socket
    #
    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass unix:/run/php/php8.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # deny access to . files, for security
    #
    location ~ /\.(?!well-known).* {
        deny all;
    }

}