user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$http_x_forwarded_for $host $uri $remote_user [$time_local] response_time=$upstream_response_time '
                      '$status $body_bytes_sent "$http_user_agent"';

    #access_log  /var/log/nginx/access.log  main;
    access_log /dev/stdout main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  605;
    client_max_body_size 120M;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}